# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/ben/venv/lib/python3.8/site-packages/qt5_applications/Py Qt Aplications/change_digit.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChangeDigit(object):
    def setupUi(self, ChangeDigit):
        ChangeDigit.setObjectName("ChangeDigit")
        ChangeDigit.resize(390, 170)
        # ChangeDigit.move(300,230)
        self.buttonBox = QtWidgets.QDialogButtonBox(ChangeDigit)
        self.buttonBox.setGeometry(QtCore.QRect(30, 130, 341, 32)) #130
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(ChangeDigit)
        self.label.setGeometry(QtCore.QRect(40, 20, 200, 18)) #191
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(ChangeDigit)
        self.comboBox.setGeometry(QtCore.QRect(30, 50, 190, 23)) #181
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.widget = QtWidgets.QWidget(ChangeDigit)
        self.widget.setGeometry(QtCore.QRect(30, 90, 301, 25))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Thousands = QtWidgets.QPushButton(self.widget)
        self.Thousands.setObjectName("Thousands")
        self.horizontalLayout.addWidget(self.Thousands)
        self.Hundreds = QtWidgets.QPushButton(self.widget)
        self.Hundreds.setObjectName("Hundreds")
        self.horizontalLayout.addWidget(self.Hundreds)
        self.Tens = QtWidgets.QPushButton(self.widget)
        self.Tens.setObjectName("Tens")
        self.horizontalLayout.addWidget(self.Tens)
        self.Ones = QtWidgets.QPushButton(self.widget)
        self.Ones.setObjectName("Ones")
        self.horizontalLayout.addWidget(self.Ones)
        self.DecimalPoint = QtWidgets.QPushButton(self.widget)
        self.DecimalPoint.setObjectName("DecimalPoint")
        self.horizontalLayout.addWidget(self.DecimalPoint)
        self.Tenths = QtWidgets.QPushButton(self.widget)
        self.Tenths.setObjectName("Tenths")
        self.horizontalLayout.addWidget(self.Tenths)
        self.Hundredths = QtWidgets.QPushButton(self.widget)
        self.Hundredths.setObjectName("Hundredths")
        self.horizontalLayout.addWidget(self.Hundredths)
        self.Thousandths = QtWidgets.QPushButton(self.widget)
        self.Thousandths.setObjectName("Thousandths")
        self.horizontalLayout.addWidget(self.Thousandths)
        self.TensOfThousandths = QtWidgets.QPushButton(self.widget)
        self.TensOfThousandths.setObjectName("TensOfThousandths")
        self.horizontalLayout.addWidget(self.TensOfThousandths)

        self.retranslateUi(ChangeDigit)
        self.buttonBox.accepted.connect(ChangeDigit.accept) # type: ignore
        self.buttonBox.rejected.connect(ChangeDigit.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ChangeDigit)

    def retranslateUi(self, ChangeDigit):
        _translate = QtCore.QCoreApplication.translate
        ChangeDigit.setWindowTitle(_translate("ChangeDigit", "Change Digit"))
        self.label.setText(_translate("ChangeDigit", "Select Which Digit to Change:"))
        self.comboBox.setItemText(0, _translate("ChangeDigit", "Wavelength/Frequency"))
        self.comboBox.setItemText(1, _translate("ChangeDigit", "Power"))
        self.Thousands.setText(_translate("ChangeDigit", "0"))
        self.Hundreds.setText(_translate("ChangeDigit", "0"))
        self.Tens.setText(_translate("ChangeDigit", "0")) #change this line back to 0
        self.Ones.setText(_translate("ChangeDigit", "0"))
        self.DecimalPoint.setText(_translate("ChangeDigit", "."))
        self.Tenths.setText(_translate("ChangeDigit", "0"))
        self.Hundredths.setText(_translate("ChangeDigit", "0"))
        self.Thousandths.setText(_translate("ChangeDigit", "0"))
        self.TensOfThousandths.setText(_translate("ChangeDigit", "0"))
